export const SYS_FONTS = [
  { label: 'Arial', value: 'Arial' },
  { label: 'Microsoft Yahei', value: 'Microsoft Yahei' },
  { label: 'Song Dynasty', value: 'SimSun' },
  { label: 'black body', value: 'SimHei' },
  { label: 'Kaiti', value: 'KaiTi' },
  { label: 'New Song Dynasty', value: 'NSimSun' },
  { label: 'FangSong', value: 'FangSong' },
  { label: 'square', value: 'PingFang SC' },
  { label: 'Chinese bold', value: 'STHeiti' },
  { label: 'Chinese regular script', value: 'STKaiti' },
  { label: 'Chinese Songti', value: 'STSong' },
  { label: 'Chinese imitation Song', value: 'STFangSong' },
  { label: 'Chinese Song Dynasty', value: 'STZhongSong' },
  { label: 'Chinese Amber', value: 'STHupo' },
  { label: 'huawenxinwei', value: 'STXinwei' },
  { label: 'Chinese official script', value: 'STLiti' },
  { label: 'Chinese regular script', value: 'STXingkai' },
  { label: 'Holly Blackbody', value: 'Hiragino Sans GB' },
  { label: 'Lantinghei SC', value: 'Lantinghei SC' },
  { label: 'Hanzipen SC', value: 'Hanzipen SC' },
  { label: 'Hannotate SC', value: 'Hannotate SC' },
  { label: 'Song Dynasty', value: 'Songti SC' },
  { label: 'Doll body', value: 'Wawati SC' },
  { label: 'Xingkai', value: 'Xingkai SC' },
  { label: 'Yuan body', value: 'Yuanti SC' },
  { label: 'Chinese silk black', value: 'STXihei' },
  { label: 'YouYuan', value: 'YouYuan' },
  { label: 'official script', value: 'LiSu' },
]

export const WEB_FONTS = [
  { label: 'Deyihei', value: 'Deyihei' },
  { label: 'Cang\'er small balls', value: 'Cang\'er small balls' },
  { label: 'Youshe title black', value: 'Youshe title black' },
  { label: 'Feng Guang Ming Rui Body', value: 'Feng Guang Ming Rui Body' },
  { label: 'Photography Modern Small Cube', value: 'Photography Modern Small Cube' },
  { label: 'station cool happy body', value: 'station cool happy body' },
  { label: 'Zhimai District Ximai Style', value: 'Zhimai District Ximai Style' },
  { label: 'Material Market Kangkangti', value: 'Material Market Kangkangti' },
  { label: 'Material Market Cool Cube', value: 'Material Market Cool Cube' },
  { label: 'Tuniu-like round body', value: 'Tuniu-like round body' },
  { label: 'Rui Zi Zhen Yan Ti', value: 'Rui Zi Zhen Yan Ti' },
]